### ISSUE TITLE
Feature Request: non async version of computeTargetCover

### ISSUE THREAD

**Issue by tposney** [trioderegion/dnd5e-helpers#154]
I'm looking to support cover in midi-qol, but don't want to reinvent the wheel, so was looking to use the dnd5e-helpers api. 

However, the method computeTargetCover is async (and as far as I can see only because of the deugLosRays. It turns out it is quite tedious to aupport an async computeTargetCover in midi-qol, but a sync version would be ideal.

Any chance of adding that to the api?

**Comment by trioderegion** [comment]
Our modules finally meet! hehe :)

At the moment, pretty much the entire Helpers team is occupied with life stuff AND we have started yet another refactor (with Kekilla's expertise).

Overall, this means I can provide a short term "no", but a long term "yes".

More specifically, I will be picking back up with dedicated Helpers development near the end of July to complete the refactor we have planned. This will include an overhaul to the Cover system that will allow a bit more flexibility in how it is used. The following snippet shows the top level operation of the rework.


    static async _targetToken(user, target, onOff){
      if(game.user !== user) return;

      const keyBind = MODULE.setting("losKeyBind");
      const confirmCover = game.keyboard._downKeys.has(keyBind) || keyBind == "";
  
      if(user.targets.size == 1 && confirmCover && onOff && MODULE.setting("losOnTarget")){
        for(const selected of canvas.tokens.controlled){
          if(selected.id === target.id) continue;
          let cover = new Cover(selected, target);
  
          //apply cover bonus automatically if requested
          if(MODULE.setting("coverApplication") == 2) await cover.addEffect();
  
          await cover.toMessage();
        }         
      }
  
      if(user.targets.size != 1)
        for(const selected of canvas.tokens.controlled)
          await Cover._removeEffect(selected);
    }
  
The creation of the Cover object (`let cover = new Cover(...)`) is a synchronous function that will do the heavy lifting of determining cover states. The application of cover effects and the output of the message will have to remain asynchronous due to foundry's API requirements.

My hope is that the `Cover` class provides increased flexibility for other modules, like Midi.

This is a bit of a long-winded explanation, but I hope it is at least somewhat satisfying.

**Comment by trioderegion** [comment]
v3.0.0 includes this rework and introduction of the "Cover" class. I will need to do another pass to make sure it is exposed and usable.

**Comment by tposney** [comment]
I look forward to it and can then test! I noticed that as of dnd 1.42
actor.data.data.attributes.ac.cover exists - do you plan to use that to set
the target AC. I hope not since I think an actor cover AC is ill considered
since cover depends on the viewpoint of the attacker.

**Comment by trioderegion** [comment]
We saw the same thing and came to the same conclusion. Helpers cover will remain as an attack penalty. 👍

**Comment by tposney** [comment]
Something odd in the implementation (or perhaps intended).  It seems that
CoverCalculator.Cover is not defined until CoverCalculator.globals() has
been called.

**Comment by trioderegion** [comment]
I believe this has been resolved v3. Please re-open if this is not the case.
