### ISSUE TITLE
[Feature Request] Options to position the Action Management HUD above or below the token

### ISSUE THREAD

**Issue by paulohdsc** [trioderegion/dnd5e-helpers#227]
I think it would be nice to have options to place the Action Management HUD directly above or below the token. If there is a resource bar configured for the token, the HUD would be shown above or below the respective resource bar.

Thanks for the great module!

**Comment by trioderegion** [comment]
Heh, funny you should ask because we got lots of blowback for the original placement of the HUD, which was above the token 😅.

On a more serious note, this request is unfortunately impractical as we require the HUD to be within the token's bounds in order to capture clicks on the HUD icons.  You could use "Enabled (Display Suppressed)" option for the hud if you wish, it will still show the used actions as status effects if you have that option enabled as well.

**Comment by paulohdsc** [comment]
Right, no problem! Thanks for your prompt response!
