### ISSUE TITLE
Undead Fortitude + Midi QoL issue

### ISSUE THREAD

**Issue by gravagehulk** [trioderegion/dnd5e-helpers#243]
I'm still running 0.8.9 for one of my games. With the latest version of Midi QoL, the Undead Fortitude isn't working correctly.

What happens is this: Character hits undead and does enough damage to down the undead. Undead fortitude pops up with the two options. Clicking normal damage makes the roll, but it resolves against a DC 6 Fortitude Save. It seems that it reads Midi QoL's result, rather than the actual damage dealt. Midi will only apply the amount of damage required to finish off the creature. So each time, the creature pops up with 1 hp and no matter how much damage the player does, the creature takes "1" damage to go to 0, per Midi QoL and the DC becomes 6 again.

Is there any way to resolve this? It's a cool feature and it at least reminds me that they have undead fortitude, but I'd love it if the automation worked correctly. Thanks.

**Comment by trioderegion** [comment]
Have you tried using “Advanced Saves” option for Undead Fortitude? The dnd5e system will only modify hp such that it hits 0 (negative values clamped), so Helpers cannot determine if there was any overkill to take into account. Sent from Mail for Windows From: gravagehulkSent: Friday, January 14, 2022 1:18 PMTo: trioderegion/dnd5e-helpersCc: SubscribedSubject: [trioderegion/dnd5e-helpers] Undead Fortitude + Midi QoL issue (Issue #243) I'm still running 0.8.9 for one of my games. With the latest version of Midi QoL, the Undead Fortitude isn't working correctly.What happens is this: Character hits undead and does enough damage to down the undead. Undead fortitude pops up with the two options. Clicking normal damage makes the roll, but it resolves against a DC 6 Fortitude Save. It seems that it reads Midi QoL's result, rather than the actual damage dealt. Midi will only apply the amount of damage required to finish off the creature. So each time, the creature pops up with 1 hp and no matter how much damage the player does, the creature takes "1" damage to go to 0, per Midi QoL and the DC becomes 6 again.Is there any way to resolve this? It's a cool feature and it at least reminds me that they have undead fortitude, but I'd love it if the automation worked correctly. Thanks.—Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

**Comment by gravagehulk** [comment]
Yeah, I just found that. Thank you. That will definitely solve my issue. I had it on "quick saves" before.
