### ISSUE TITLE
Suggestion: better place to the actions track

### ISSUE THREAD

**Issue by Fridan99** [trioderegion/dnd5e-helpers#253]
I think it would be useful to place or be able to place the action track of the combat helspers somewhere else instead of inside the token. In the following image you can see how when the token has several effects, the track is not visible. 

![Track actions](https://user-images.githubusercontent.com/86131373/156164898-485592ca-0557-4000-b3dc-018a9de272a0.jpg)

Another more intuitive help would be the possibility of replacing the images of the track.... by the letters A (action) B (Bonus action) R (reaction).... and could be somewhat more visible, the gray color in certain circumstances can be difficult to see. 
The figures are not too intuitive when identifying the track, at least my players have had problems to identify them xD.... I honestly have no problem. 

Well it is a simple suggestion, in case you consider that it is useful or improves the fabulous module.

**Comment by trioderegion** [comment]
If im understanding correctly, part of this problem is that the HUD module you are using is compressing the controls such that they overlap the token? Or because Perfect Vision is gray-scaling the scene?

For technical reasons, we have to keep the Action HUD inside the token bounds. The icon selection itself is a tricky problem because adding a letter badge to those icons would be both too small and too noisy in the display space. However, replacing the whole icon with a letter will then alienate non-English speakers.

You aren't wrong that there are some UX issues though.

**Comment by Fridan99** [comment]
The problem is that the track indicators are hidden behind the states (effects, spells, concentration.....) and also when you don't have any effect they are slightly complicated to see..... they look "very dim".

I don't see any other idea than outsourcing them outside the token or at least I can't think of, and I understand that it can be complicated or cumbersome. :P

Well it's just a little constructive criticism, giving my humble point of view. 

Good job for this module.

**Comment by trioderegion** [comment]
> The problem is that the track indicators are hidden behind the states (effects, spells, concentration.....)

This may actually be a problem. Could you screen shot this? We modify how statuses are drawn in order to prevent this overlap from happening.

**Comment by Fridan99** [comment]
![track](https://user-images.githubusercontent.com/86131373/159336913-b5a5f522-ab8b-4433-8fd7-45fb218ba290.jpg)

The track is behind of the concentration icon, and so on with all icons effects.

**Comment by trioderegion** [comment]
gotchya, can do you a quick test and turn off status effect scaling via CUB (?). And modify the current effect scaling option in helpers? Default is 1, try changing to 1.2.
