### ISSUE TITLE
Feature Request: Enhanced Regeneration Automation

### ISSUE THREAD

**Issue by R-Jimenez** [trioderegion/dnd5e-helpers#84]
First off, awesome work here. I was actually considering building my own module to handle this case as well as a few other automation tools (one of which was action/bonus action management even), but great devs like yourselves just seem to keep beating me to the punch.

This is a pretty minor request, but it would be nice to be able to specify a CUB condition for the Regeneration check (similar to the Reaction check) that can augment the workflow as follows:
1. Creature turn starts, check to see if it has condition specified in settings (ex. "Regen Blocked").
2. If condition exists, don't prompt GM for regen. Otherwise prompt for amount as usual.
3. In either case remove specified condition. (This could potentially be a setting, but not really necessary for the cases I can think of)

In larger combats with undead, it can be a mess keeping track of which ones have or haven't been triggered that turn, so I've taken to using a custom condition to keep track of things. This is a relatively extraneous feature, but would be a neat little bow over things and perhaps give other GMs the idea to keep things clean if they ever find themselves in a vampire horde.

Cheers!

**Comment by R-Jimenez** [comment]
Regen prompt is blocked if ${Condition} (specified in settings, like Reaction controls does) is present on the actor at the start of their turn.

In a combat with many actors that have regen, whenever one gets hit with damage that turns off the ability, I toggle on a condition (ex. Regen_Blocked). Then when it gets to their turn I can tell whether or not they had something hit during the round that stops me from hitting the magic button. I then remove the condition and play their turn. This workflow works fine, the check of condition here would automate things only slightly.

The removal is what I'm having trouble doing without some JS of my own, as both CUB and DAE don't have a mechanism to specify a duration of "Until next turn" for a custom CUB condition. Since I noticed this was very similar to something your module was already doing (apply Reaction, unapply on start of turn), I figured it wouldn't be too difficult to clone the behavior, and would augment the existing functionality.

**Comment by trioderegion** [comment]
Thank you for the explanation, I understand better now.

A flag (active effect condition) could reasonably be used to dodge the prompt.

However, I need to push back a little on the removal of this flag at the start of a turn. The philosophy of Helpers is that we will automate any 5e actions that have _zero_ decision points.  Take, for example, a Troll's regen, which is blocked by fire or acid. Beginning of turn removal of the Blocked status is a no-decision point.  However, looking at the Vampire's regen, they do not regen as long as they are in direct sunlight (in addition to receiving radiant damage for a turn).  This creature's regen requires a decision point -- "is the creature in direct sunlight".

Due to this potential decision point, I am less inclined to automate the removal of the blocked condition. Additionally, other modules such as About Time (or Times Up?) can automate the removal of statuses on a round by round basis.

I'd like to loop in @kandashi for their thoughts on this.

In summation: Detecting a pre-defined status (Reaction Blocked) and suppressing the regen prompt is appropriate for 5e Helpers. Automatically removing said status is a bit outside the scope of Helpers due to the decision point required.

**Comment by kandashi** [comment]
I think @trioderegion that is a good summary. I think something along the lines of "blocked regen" as @R-Jimenez suggests would be a good mid-point. Not testing every type of regen for the specific blocking, but still providing the option

**Comment by kandashi** [comment]
Complete in 1.11.0
